CREATE TABLE merchant (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  merchant_name VARCHAR(128) NOT NULL,
  contact_name VARCHAR(64),
  phone VARCHAR(32),
  location VARCHAR(256),
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dish (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  category_id BIGINT,
  merchant_id BIGINT,
  price DECIMAL(10, 2) NOT NULL,
  image VARCHAR(256),
  description TEXT,
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES category(id),
  FOREIGN KEY (merchant_id) REFERENCES merchant(id)
);

CREATE TABLE dish_flavor (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dish_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  value VARCHAR(64) NOT NULL,
  FOREIGN KEY (dish_id) REFERENCES dish(id)
);

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  name VARCHAR(64),
  phone VARCHAR(32),
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE address_book (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  consignee VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  address VARCHAR(256) NOT NULL,
  is_default TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE shopping_cart (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  dish_flavor VARCHAR(64),
  number INT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (dish_id) REFERENCES dish(id)
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  `number` VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  status TINYINT DEFAULT 1,
  amount DECIMAL(10, 2) NOT NULL,
  order_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  checkout_time DATETIME,
  pay_method VARCHAR(32),
  pay_status TINYINT DEFAULT 0,
  consignee VARCHAR(64),
  phone VARCHAR(32),
  address VARCHAR(256),
  remark TEXT,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE order_detail (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  dish_flavor VARCHAR(64),
  number INT NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  image VARCHAR(256),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (dish_id) REFERENCES dish(id)
);