server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  application:
    name: sky-server
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: isDeleted
        logic-delete-value: 1
        logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh_cn

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.neu.controller

logging:
  level:
    com.neu: debug
    org.mybatis: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
